# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mti/github-tomerten/IBSlib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mti/github-tomerten/IBSlib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mti/github-tomerten/IBSlib/CMakeFiles /home/mti/github-tomerten/IBSlib/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mti/github-tomerten/IBSlib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named clog

# Build rule for target.
clog: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clog
.PHONY : clog

# fast build rule for target.
clog/fast:
	$(MAKE) -f CMakeFiles/clog.dir/build.make CMakeFiles/clog.dir/build
.PHONY : clog/fast

#=============================================================================
# Target rules for targets named numfunc

# Build rule for target.
numfunc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 numfunc
.PHONY : numfunc

# fast build rule for target.
numfunc/fast:
	$(MAKE) -f CMakeFiles/numfunc.dir/build.make CMakeFiles/numfunc.dir/build
.PHONY : numfunc/fast

#=============================================================================
# Target rules for targets named IBSLib

# Build rule for target.
IBSLib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IBSLib
.PHONY : IBSLib

# fast build rule for target.
IBSLib/fast:
	$(MAKE) -f CMakeFiles/IBSLib.dir/build.make CMakeFiles/IBSLib.dir/build
.PHONY : IBSLib/fast

CoulombLog/CoulombLogFunctions.o: CoulombLog/CoulombLogFunctions.cpp.o

.PHONY : CoulombLog/CoulombLogFunctions.o

# target to build an object file
CoulombLog/CoulombLogFunctions.cpp.o:
	$(MAKE) -f CMakeFiles/clog.dir/build.make CMakeFiles/clog.dir/CoulombLog/CoulombLogFunctions.cpp.o
.PHONY : CoulombLog/CoulombLogFunctions.cpp.o

CoulombLog/CoulombLogFunctions.i: CoulombLog/CoulombLogFunctions.cpp.i

.PHONY : CoulombLog/CoulombLogFunctions.i

# target to preprocess a source file
CoulombLog/CoulombLogFunctions.cpp.i:
	$(MAKE) -f CMakeFiles/clog.dir/build.make CMakeFiles/clog.dir/CoulombLog/CoulombLogFunctions.cpp.i
.PHONY : CoulombLog/CoulombLogFunctions.cpp.i

CoulombLog/CoulombLogFunctions.s: CoulombLog/CoulombLogFunctions.cpp.s

.PHONY : CoulombLog/CoulombLogFunctions.s

# target to generate assembly for a file
CoulombLog/CoulombLogFunctions.cpp.s:
	$(MAKE) -f CMakeFiles/clog.dir/build.make CMakeFiles/clog.dir/CoulombLog/CoulombLogFunctions.cpp.s
.PHONY : CoulombLog/CoulombLogFunctions.cpp.s

NumericFunctions/NumericFunctions.o: NumericFunctions/NumericFunctions.cpp.o

.PHONY : NumericFunctions/NumericFunctions.o

# target to build an object file
NumericFunctions/NumericFunctions.cpp.o:
	$(MAKE) -f CMakeFiles/numfunc.dir/build.make CMakeFiles/numfunc.dir/NumericFunctions/NumericFunctions.cpp.o
.PHONY : NumericFunctions/NumericFunctions.cpp.o

NumericFunctions/NumericFunctions.i: NumericFunctions/NumericFunctions.cpp.i

.PHONY : NumericFunctions/NumericFunctions.i

# target to preprocess a source file
NumericFunctions/NumericFunctions.cpp.i:
	$(MAKE) -f CMakeFiles/numfunc.dir/build.make CMakeFiles/numfunc.dir/NumericFunctions/NumericFunctions.cpp.i
.PHONY : NumericFunctions/NumericFunctions.cpp.i

NumericFunctions/NumericFunctions.s: NumericFunctions/NumericFunctions.cpp.s

.PHONY : NumericFunctions/NumericFunctions.s

# target to generate assembly for a file
NumericFunctions/NumericFunctions.cpp.s:
	$(MAKE) -f CMakeFiles/numfunc.dir/build.make CMakeFiles/numfunc.dir/NumericFunctions/NumericFunctions.cpp.s
.PHONY : NumericFunctions/NumericFunctions.cpp.s

libtest.o: libtest.cpp.o

.PHONY : libtest.o

# target to build an object file
libtest.cpp.o:
	$(MAKE) -f CMakeFiles/IBSLib.dir/build.make CMakeFiles/IBSLib.dir/libtest.cpp.o
.PHONY : libtest.cpp.o

libtest.i: libtest.cpp.i

.PHONY : libtest.i

# target to preprocess a source file
libtest.cpp.i:
	$(MAKE) -f CMakeFiles/IBSLib.dir/build.make CMakeFiles/IBSLib.dir/libtest.cpp.i
.PHONY : libtest.cpp.i

libtest.s: libtest.cpp.s

.PHONY : libtest.s

# target to generate assembly for a file
libtest.cpp.s:
	$(MAKE) -f CMakeFiles/IBSLib.dir/build.make CMakeFiles/IBSLib.dir/libtest.cpp.s
.PHONY : libtest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... clog"
	@echo "... numfunc"
	@echo "... IBSLib"
	@echo "... CoulombLog/CoulombLogFunctions.o"
	@echo "... CoulombLog/CoulombLogFunctions.i"
	@echo "... CoulombLog/CoulombLogFunctions.s"
	@echo "... NumericFunctions/NumericFunctions.o"
	@echo "... NumericFunctions/NumericFunctions.i"
	@echo "... NumericFunctions/NumericFunctions.s"
	@echo "... libtest.o"
	@echo "... libtest.i"
	@echo "... libtest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

